CLASSPATH=$DEV_HOME/target/heffalump-1.0.jar:\
/usr/lib/hadoop/*:\
/usr/lib/hadoop/client/*:\
/usr/share/java/*:\
$DEV_HOME/scripts/lib/JSON-1.0.jar:\
$DEV_HOME/scripts/lib/junit-4.9.jar:\
$DEV_HOME/scripts/lib/log4j.jar:\
$DEV_HOME/scripts/lib/mahout-core-0.7.jar:\
$DEV_HOME/scripts/lib/guava-13.0.1.jar:\
$DEV_HOME/scripts/lib/mahout-math-0.7.jar:\
$DEV_HOME/scripts/lib/uncommons-maths-1.2.2a.jar:
